CREATE TABLE employees (
    emp_id NUMBER PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    dept VARCHAR2(50) NOT NULL,
    desig VARCHAR2(50) NOT NULL,
    join_date DATE NOT NULL,
    base_salary NUMBER(10,2) NOT NULL,
    status VARCHAR2(20) NOT NULL
);

CREATE TABLE attendance (
    att_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id NUMBER NOT NULL,
    date_col DATE NOT NULL,
    status VARCHAR2(10) NOT NULL,
    CONSTRAINT fk_att_emp FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
);

CREATE TABLE payroll (
    payroll_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id NUMBER NOT NULL,
    month NUMBER(2) NOT NULL,
    year NUMBER(4) NOT NULL,
    gross NUMBER(10,2) NOT NULL,
    deductions NUMBER(10,2) NOT NULL,
    net NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_pay_emp FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
);